create table if not exists Persons (
    id int generated by default as identity primary key,
    firstName varchar(100) not null,
    surname varchar(100) not null,
    patronymic varchar(100),
    nickname varchar(100) not null unique,
    password text not null,
    email text not null unique,
    created_at timestamp not null,
    updated_at timestamp not null,
    created_who varchar(25) not null
);

create table if not exists authorities(
    id int generated by default as identity primary key,
    authority_name varchar(50) not null unique
);

create table if not exists persons_authorities(
    person_id int references persons(id),
    authority_id int references authorities(id),
    primary key (person_id, authority_id)
)