create table if not exists Persons (
    id int8 generated by default as identity primary key,
    firstName varchar(100) not null,
    surname varchar(100) not null,
    patronymic varchar(100),
    nickname varchar(100) not null unique,
    password text not null,
    email text not null unique,
    isEmailVerified bool not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    created_who varchar(25) not null
);

create table if not exists roles(
    id int8 generated by default as identity primary key,
    role_name varchar(50) not null unique
);

create table if not exists persons_roles(
    person_id int8 references persons(id),
    role_id int8 references roles(id),
    primary key (person_id, role_id)
);

insert into roles(role_name) values ('ANONYMOUS') on conflict do nothing;
insert into roles(role_name) values ('USER') on conflict do nothing;
insert into roles(role_name) values ('ADMIN') on conflict do nothing;
insert into roles(role_name) values ('ROOT') on conflict do nothing;