FROM postgres:15

# Установка переменных окружения (лучше не использовать напрямую в проде)
ENV POSTGRES_DB=some_db \
    POSTGRES_USER=some_user \
    POSTGRES_PASSWORD=some_password

EXPOSE 5432

VOLUME ["/var/lib/postgresql/data"]
